<?php
/**
 * Template for filter items block
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
 */
?>
<?php
$priceDisplayMode = $this->helper('Infobeans\MultiFilter\Helper\Data')->getConfig('multifilter/general/display_mode');
if ($filter->getName() == 'Price' && $priceDisplayMode == 'slider'):
    ?>
    <?php $range = $this->getPriceRange($filter); ?>
    <?php $url = $this->getFilterUrl($filter); ?>
    <?php //var_dump($url);  ?>
    <script>
        var price_url = "<?= $url; ?>";
        require([
            'jquery',
            "jquery/ui",
            'domReady!'
        ], function($){
            var selectedFilter = [];
            //     `use strict`;
            console.log("Price Slider..!");
            //require(["jquery" , "jquery/jquery-ui"], function($){
            // ...
            $("div#price-slider").slider({
                range: true,
                min: <?= $range['min'] ?>,
                max: <?= $range['max'] ?>,
                values: [ <?= $range['min'] ?>, <?= $range['max'] ?> ],
                slide: function( event, ui ) {
                    $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
                },
                change: function( event, ui ) {
                    //alert(ui.values[0]+"~"+ui.values[1]);
                    var text = "attribute?price?";
                    $('#sliderprice').val(text+ui.values[0]+"-"+ui.values[1]);
                }
            });
            $( "#amount" ).val( "$" + $( "#price-slider" ).slider( "values", 0 ) +
                " - $" + $( "#price-slider" ).slider( "values", 1 ) );
            
        });
    </script>
    <?php ?>      
    <p>
        <input type="text" id="amount" readonly style="border:0; color:#1979c3; font-weight:bold;">
    </p>
    <div id="price-slider"></div>

<?php else: ?>
    <ol class="items">
        <?php
        $showProductCount = $this->helper('Infobeans\MultiFilter\Helper\Data')->getConfig('multifilter/general/product_count');
        foreach ($filterItems as $filterItem):
            $parameters = substr($filterItem->getUrl(), strpos($filterItem->getUrl(), "?") + 1);
            $arr = explode('=', $parameters);
            ?>
            <li class="item" id="filterlist">
                <?php if ($arr[0] == 'cat') { ?>
                    <input type="checkbox" id="<?php echo $arr[1]; ?>" class="multifilter" value="<?php echo 'category' . '?' . $arr[0] . '?' . $arr[1]; ?>">
                <?php } else { ?>
                    <input type="checkbox" id="<?php echo $arr[1]; ?>" class="multifilter" value="<?php echo 'attribute' . '?' . $arr[0] . '?' . $arr[1]; ?>">
                <?php } ?>
                    <input type="hidden" id="sliderprice" class="multifilter" value="">
                <?php if ($filterItem->getCount() > 0):
                    ?>
                    <a href="javascript:void(0)">
                        <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                        <?php
                        //Multifilter : Condition for showning product count depanding upon system configuration for product display count
                        if ($showProductCount == '1') {
                            if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()):
                                ?>
                                <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getCount() ?><span class="filter-count-label">
                                        <?php if ($filterItem->getCount() == 1): ?> <?php /* @escapeNotVerified */ echo __('item') ?><?php else: ?> <?php /* @escapeNotVerified */ echo __('items') ?><?php endif; ?></span></span>
                                <?php
                            endif;
                        }
                        ?>
                    </a>
                <?php else: ?>
                    <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                    <?php
                    //Multifilter : Condition for showning product count depanding upon system configuration for product display count
                    if ($showProductCount == '1') {
                        if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()):
                            ?>
                            <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getCount() ?><span class="filter-count-label">
                                    <?php if ($filterItem->getCount() == 1): ?><?php /* @escapeNotVerified */ echo __('item') ?><?php else: ?><?php /* @escapeNotVerified */ echo __('items') ?><?php endif; ?></span></span>
                                    <?php
                                endif;
                            }
                            ?>
                        <?php endif; ?>
            </li>
        <?php endforeach ?>
    </ol>
<?php endif; ?>
    
        